# -*- coding: utf-8 -*-
"""Week 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gBq-E_xOUS8X0y0DOJmkx09XXy2HxIjt
"""
# this notebook will be mainly used for the capstone project
import pandas as pd
import numpy as np

print("Hello Capstone Project Course!")
